name: Cleanup old branches
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@6e94df089372a619c01ae2c2f666bf474f890911 # v0.0.10
        with:
          repo_token: ${{ github.token }}
          date: '3 months ago'
          dry_run: false
          delete_tags: false
          exclude_open_pr_branches: true
